package com.server.anki.message;

public enum MessageType {
    ORDER_CREATED,
    ORDER_ACCEPTED,
    ORDER_STATUS_UPDATED,
    REVIEW_RECEIVED,
    TICKET_REPLIED,
    TICKET_STATUS_UPDATED,
    QUESTION_REPLIED,
    QUESTION_SOLUTION_APPLIED,
    QUESTION_SOLUTION_ACCEPTED,
    QUESTION_RESOLVED,
    QUESTION_SOLUTION_REJECTED,
    QUESTION_STATUS_UPDATED,
    WALLET_RECHARGE_SUCCESS,    // 充值成功
    WALLET_WITHDRAW_SUCCESS,    // 提现成功
    WALLET_WITHDRAW_FAILED,
    ORDER_PAYMENT_TIMEOUT,// 提现失败
    ORDER_PAYMENT_CREATED,    // 支付订单创建
    ORDER_PAYMENT_SUCCESS,    // 支付成功
    ORDER_PAYMENT_CANCELLED, // 支付取消
    ORDER_REFUND_PROCESSING, // 退款处理中
    WALLET_REFUND,
    BILLING_INFO,
    ORDER_WARNING,
    STORE_NEW_ORDER,
    ORDER_REFUND_SUCCESS,
    ORDER_DELIVERED,
    ORDER_COMPLETED,
    ORDER_REFUND_REQUESTED,
    PRODUCT_STATUS_UPDATED
}